wamv_camera:
    - name: side_left_camera
      x: 0.0
      y: 0.48
      P: ${radians(15)}
      Y: ${radians(90)}
    - name: side_right_camera
      x: 0.0
      y: -0.48
      P: ${radians(15)}
      Y: ${radians(-90)}
    - name: front_center_camera
      x: 0.75
      y: 0.0
      P: ${radians(15)}
      
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
      x: 0.6
      y: 0.0
lidar:
    - name: lidar_wamv
      type: 16_beam
      
